config/routes.rb
Rails.application.routes.draw do
  get 'records/new'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'main#index'

  resources :musics
  resources :main
  resources :posts, only: [:index]
  resources :tapes
  resources :dailies
  resources :my_pages
  resources :records do
    get 'add/:id', :to => "records#add", as: 'add', on: :collection
  end

  get 'teasers/index'
  get 'main/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily.rb
class Daily < ApplicationRecord
  belongs_to :user
  has_many :musics, :as => :fantastic
end

app/models/music.rb
class Music < ApplicationRecord

end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :musics
end

app/models/tape.rb
class Tape < ApplicationRecord
  belongs_to :user
  belongs_to :m1, class_name: 'Music', foreign_key: 'm1', optional: true
  belongs_to :m2, class_name: 'Music', foreign_key: 'm2', optional: true
  belongs_to :m3, class_name: 'Music', foreign_key: 'm3', optional: true
  (4..10).to_a.each do |i|
    belongs_to "m#{i}".to_sym, class_name: 'Music', foreign_key: "m#{i}", optional: true
  end
  has_many :musics, :as => :fantastic
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tapes
  has_many :dailies
  has_many :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  def index

  end

  def new
    @daily = Daily.new

    @musics = Music.all

    @music_tscollection = Array.new()
    @musics.each do |music|
      @music_tscollection.push music.ts
    end
  end

  def create
    daily = Daily.new

    daily.user_id = current_user.id
    daily.daily_title = params[:daily][:daily_title]
    daily.musicN = params[:daily][:musicN]
    daily.body = params[:daily][:body]
    daily.save

    redirect_to new_daily_path
  end

  def update
    @daily = Daily.find_by.params[:daily_id]
  end

  def edit
    @daily = Daily.find_by.params[:daily_id]
  end

  def show
    @daily = Daily.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def show
  end

  # def show
  # end
end

app/controllers/my_pages_controller.rb
class MyPagesController < ApplicationController
  def index
    list = []
    current_user.records.each { |x| list << x.music_id }
    # Record.where(user_id: current_user.id).each { |x| list << x.music_id }

    @list = Music.find(list)

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def new
    @list = Record.new


    @musics = Music.all

    @music_tscollection = Array.new()
    @musics.each do |music|
      @music_tscollection.push music.ts
    end
    # @list.user_id = current_user.id
    # @list.music_id = params[:record][:music_id]
    # @list.save
    #
    # redirect_to root_path
  end

  def create
    list = record_params.values

    list[0].each do |x|
      @list = Record.new
      @list.music_id = x
      @list.user_id = current_user.id
      @list.save
    end

    tape_list = Record.where(user_id: current_user.id).last(10)

    tape = Tape.new
    tape.tape_title = "인생열곡"
    tape.user_id = current_user.id
    tape.m1 = Music.find_by(id: tape_list[0].music_id)
    tape.m2 = Music.find_by(id: tape_list[1].music_id)
    tape.m3 = Music.find_by(id: tape_list[2].music_id)
    tape.m4 = Music.find_by(id: tape_list[3].music_id)
    tape.m5 = Music.find_by(id: tape_list[4].music_id)
    tape.m6 = Music.find_by(id: tape_list[5].music_id)
    tape.m7 = Music.find_by(id: tape_list[6].music_id)
    tape.m8 = Music.find_by(id: tape_list[7].music_id)
    tape.m9 = Music.find_by(id: tape_list[8].music_id)
    tape.m10 = Music.find_by(id: tape_list[9].music_id)
    tape.save

    redirect_to root_path
  end

  def add

    record = Record.new
    record.user_id = current_user.id
    record.music_id = params[:id]
    record.save

    redirect_back(fallback_location: root_path)
  end

  private
  def record_params
      params.require(:record).permit(:music_id => [])
    end
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  def index
    @tapes = Tape.all
  end

  def new
    @tape = Tape.new
    @musics = Music.all
    @music_tscollection = Music.pluck(:ts)
  end

  def edit
    @tape = Tape.find(params[:id])
    @musics = Music.all
    @music_tscollection = Music.pluck(:ts)
  end

  def update
    tape = Tape.find(params[:id])
    (1..10).to_a.each do |i|
      current_music = "m#{i}".to_sym
      music = nil
      if tape_params[current_music].present?
        music = Music.find_by_ts(tape_params[current_music][:ts])
      end
      tape_params[current_music] = music
    end
    tape.update!(tape_params)
    # tape.save!
    redirect_to edit_tape_path(tape), notice: "수정되었습니다."
  end

  def create
    @correct_music1 = Music.find_by_ts(params[:tape][:m1][:ts])
    @correct_music2 = Music.find_by_ts(params[:tape][:m2][:ts])
    @correct_music3 = Music.find_by_ts(params[:tape][:m3][:ts])
    @correct_music4 = Music.find_by_ts(params[:tape][:m4][:ts])
    @correct_music5 = Music.find_by_ts(params[:tape][:m5][:ts])
    @correct_music6 = Music.find_by_ts(params[:tape][:m6][:ts])
    @correct_music7 = Music.find_by_ts(params[:tape][:m7][:ts])
    @correct_music8 = Music.find_by_ts(params[:tape][:m8][:ts])
    @correct_music9 = Music.find_by_ts(params[:tape][:m9][:ts])
    @correct_music10 = Music.find_by_ts(params[:tape][:m10][:ts])

    tape = Tape.new

    tape.tape_title = params[:tape][:tape_title]
    tape.user_id = current_user.id
    tape.m1 = @correct_music1 || nil
    tape.m2 = @correct_music2 || nil
    tape.m3 = @correct_music3 || nil
    tape.m4 = @correct_music4 || nil
    tape.m5 = @correct_music5 || nil
    tape.m6 = @correct_music6 || nil
    tape.m7 = @correct_music7 || nil
    tape.m8 = @correct_music8 || nil
    tape.m9 = @correct_music9 || nil
    tape.m10 = @correct_music10 || nil
    tape.save
    redirect_to edit_tape_path(tape), notice: "테이프에 노래가 들어갔습니다."
  end


  def show
    @tape = Tape.find_by(id: params[:id])

    song = []
    song << @tape.m1
    song << @tape.m2
    song << @tape.m3
    song << @tape.m4
    song << @tape.m5
    song << @tape.m6
    song << @tape.m7
    song << @tape.m8
    song << @tape.m9
    song << @tape.m10

    @list = Music.where(id: song)
  end

  private

  def found_music(param)
    result = nil
    if param.is_a?(String)
      result = Music.find_by_ts(params[:tape][:m1])
    elsif param.is_a?(Music)
      result = Music.find_by_ts(params[:tape][:m1])
    end
    result
  end

  def set_data
    @tape = find_by.params[:tape_id]
  end

  def tape_params
    params.require(:tape).permit!
  end
end

app/controllers/teasers_controller.rb
class TeasersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/helpers/teasers_helper.rb
module TeasersHelper
end

app/views/dailies/_form.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

<script>
  $(function(){
    var index = <%=raw @music_tscollection %>
    $(".music_placeholder").autocomplete({
      source: index
    });
  });
</script>

<%= form_for @daily do |d| %>

  <div class="form_section_one">

    <%= d.label class: "form_title", for: "daily_title" do %>제목
      <%= d.text_field :daily_title, class: "title_placeholder", placeholder: "제목을 작성해주세요" %>
    <% end %>

    <%= d.label class: "form_track", for: "musicN" do %>트랙
      <%= d.text_field :musicN, class: "music_placeholder", placeholder: "곡을 녹음해주세요" %>
    <% end %>


    <div class="tape_img_container">
      <%= d.label :사진, class: "form_dailyimg" %>
      <div class="input_img">
        <%= d.label :사진을등록해주세요, class: "img_placeholder", for: "daily_img" %>
        <%= d.file_field :img, id: "daily_img", class: 'upload_dailyimg' %>
      </div>
    </div>

  </div>


  <div class="form_section_two">

    컬러

    <div class="daily_color_btns">
      <button type="button" class="daily_black_btn" onclick="changingBlack()"></button>
      <button type="button" class="daily_gray_btn" onclick="changingGray()"></button>
      <button type="button" class="daily_pink_btn" onclick="changingPink()"></button>

      <button type="button" class="daily_orange_btn"  onclick="changingOrange()"></button>
      <button type="button" class="daily_yellow_btn"  onclick="changingYellow()"></button>
      <button type="button" class="daily_mint_btn" onclick="changingMint()"></button>
      <button type="button" class="daily_blue_btn" onclick="changingBlue()"></button>
      <button type="button" class="daily_purple_btn" onclick="changingPurple()"></button>
    </div>

    <script>
      function changingBlack() {
        document.getElementById("daily_color_modal").style.backgroundColor = "gray";
      }
      function changingGray() {
        document.getElementById("daily_color_modal").style.backgroundColor = "lightgray";
      }
      function changingYellow() {
        document.getElementById("daily_color_modal").style.backgroundColor = "yellow";
      }
      function changingOrange() {
        document.getElementById("daily_color_modal").style.backgroundColor = "orange";
      }
      function changingPink() {
        document.getElementById("daily_color_modal").style.backgroundColor = "pink";
      }
      function changingMint() {
        document.getElementById("daily_color_modal").style.backgroundColor = "green";
      }
      function changingBlue() {
        document.getElementById("daily_color_modal").style.backgroundColor = "blue";
      }
      function changingPurple() {
        document.getElementById("daily_color_modal").style.backgroundColor = "purple";
      }
    </script>

</div>


  <div class="form_section_three">
    <%= d.label class: "form_title", for: "body" do %>일기
      <%= d.text_area :body, rows: 5, class: "textarea_box", placeholder: "내용을 작성해주세요" %>
    <% end %>
  </div>

  <div class="form_section_four">
    <!-- <button type="submit" value="save" id="form_submit_btn"> 저장 </button> -->
    <%= d.submit "저장", id: "form_submit_btn" %>
  </div>


<% end %>

app/views/dailies/_save.html.erb
<!-- Daily_Card -->

<section class="view_container_daily">

  <section class="nav_daily">
    <h1 class="title_daily">데일리 뮤직</h1>
  </section>

  <section class="body_daily">
    <p class="intro_daily">당신의 플레이리스트와 꼭 맞는 유저들의 오늘의 음악이에요.</p>

    <div class="daily_card_container">
      <a id="card1" class="daily_card">
          <!-- <!— 사용자 데일리의 컬러 —> -->
          <div class="daily_card_color">
          <!-- <!— 사용자 데일리의 제목 —> -->
            <p class="daily_card_title">우리는 지금 어디에</p>
          </div>
          <div class="daily_card_img_box">
            <!-- <!— 사용자 데일리의 이미지 —> -->
            <img class="daily_card_img" src="/assets/daily_ex.jpg"></img>
          </div>

      </a>
      <a id="card2" class="daily_card">
          <!-- <!— 사용자 데일리의 컬러 —> -->
          <div class="daily_card_color">
          <!-- <!— 사용자 데일리의 제목 —> -->
            <p class="daily_card_title">잔망속에서</p>
          </div>
          <div class="daily_card_img_box">
            <!-- <!— 사용자 데일리의 이미지 —> -->
            <img class="daily_card_img" src="/assets/daily_ex.jpg"></img>
          </div>
      </a>

      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
      <div class="daily_card">
        <div class="daily_card_color"></div>
        <div class="daily_card_img_box"></div>
      </div>
    </div>

  </section>

  <section class="ad_daily">
    <p class="logo_daily">늘어진<br>카세트<br>테이프</p>
  </section>



</section>


<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal_container">
    <span class="close">&times;</span>
    <!-- <!— 사용자 데일리의 컬러 (모달) —> -->
    <div class="daily_color_modal">
      <!-- <!— 사용자 데일리의 제목 (모달) —> -->
      <p class="daily_title_modal">우리는 지금 어디</p>
    </div>
    <div class="daily_img_box_modal">
      <!-- <!— 사용자 데일리의 사진 (모달) —> -->
      <img class="daily_img_modal" src="/assets/daily_ex.jpg">
    </div>
    <div class="user_context_modal">
      <!-- <!— 사용자 데일리의 노래 제목, 가수 (모달) —> -->
      <p class="daily_song_modal">잘 가요 로맨스 - 박선주</p>

      <input type="image" id="rec_btn" alt="rec"
           src="/assets/rec_btn_black@3x.jpg" onclick="document.getElementById('rec_btn').src='/assets/rec_btn_red@3x.jpg'">

      <!-- <!— 사용자 데일리의 텍스트내용1 (모달) —> -->
      <!-- 공백포함 글자수163 , byte 수 285 byte-->
      <p class="daily_text">랜덤 재생 모드로 음악을 듣다가 어느 순간 박선주의 ‘잘가요 로맨스’가 나온다. 전주 뒤에 첫 단어를 박선주가 노래하자마자 나는 도쿄의 좁디 좁은 호텔방에 누워있다. 그저 하얀 침대커버 왼쪽 모서리에 베개도 안 베고 오른쪽으로 돌아누운 채로
      </p>
    </div>
    <div class="user_context_modal2">
      <!-- <!— 사용자 데일리의 텍스트내용1 (모달) —> -->
      <!-- 공백포함 글자수169 , byte 수 289 byte-->
      <p class="daily_text2">바로 앞에 있는 나무 합판으로 만들어진 책상을 응시하고 있다. 온도는 반팔을 입고 있기에 딱 적당한 것 같은 온도, 창문 앞에 있는 싸구려 히터가 털털털 돌아가고 있는 것 같고, 건조한 것 같은 화장실은 살짝 문이 열려있다. 그냥 그렇게 있다.</p>

      <div class="by_user_nick_box">
        <span>by</span>
        <!-- <!— 사용자 데일리의 닉네임 (모달) —> -->
        <p class="daily_user_nick">피가로</p>
      </div>

    </div>

  </div>

</div>

<!-- The Modal2 -->
<div id="myModal2" class="modal">

  <!-- Modal content -->
  <div class="modal_container">
    <span class="close">&times;</span>
    <!-- <!— 사용자 데일리의 컬러 (모달) —> -->
    <div class="daily_color_modal">
      <!-- <!— 사용자 데일리의 제목 (모달) —> -->
      <p class="daily_title_modal">잔망속에서</p>
    </div>
    <div class="daily_img_box_modal">
      <!-- <!— 사용자 데일리의 사진 (모달) —> -->
      <img class="daily_img_modal" src="/assets/daily_ex.jpg">
    </div>
    <div class="user_context_modal">
      <!-- <!— 사용자 데일리의 노래 제목, 가수 (모달) —> -->
      <p class="daily_song_modal">잘 가요 로맨스 - 박선주</p>

      <input type="image" id="rec_btn2" alt="rec"
           src="/assets/rec_btn_black.png" onclick="document.getElementById('rec_btn2').src='/assets/rec_btn_red.png'">

      <!-- <!— 사용자 데일리의 텍스트내용1 (모달) —> -->
      <p class="daily_text">랜덤 재생 모드로 음악을 듣다가 어느 순간 박선주의 ‘잘가요 로맨스’가 나온다. 전주 뒤에 첫 단어를 박선주가 노래하자마자 나는 도쿄의 좁디 좁은 호텔방에 누워있다. 그저 하얀 침대커버 왼쪽 모서리에 베개도 안 베고 오른쪽으로 돌아누운 채로
      </p>
    </div>
    <div class="user_context_modal2">
      <!-- <!— 사용자 데일리의 텍스트내용1 (모달) —> -->
      <p class="daily_text2">바로 앞에 있는 나무 합판으로 만들어진 책상을 응시하고 있다. 온도는 반팔을 입고 있기에 딱 적당한 것 같은 온도, 창문 앞에 있는 싸구려 히터가 털털털 돌아가고 있는 것 같고, 건조한 것 같은 화장실은 살짝 문이 열려있다. 그냥 그렇게 있다. </p>

      <div class="by_user_nick_box">
        <span>by</span>
        <!-- <!— 사용자 데일리의 닉네임 (모달) —> -->
        <p class="daily_user_nick">피가로</p>
      </div>

    </div>

  </div>

</div>


<script>
// Get the modal
var modal = document.getElementById('myModal');
var modal2 = document.getElementById('myModal2');


// Get the button that opens the modal
// var btn = document.getElementById("myBtn");
var cardbtn = document.getElementById("card1");
var cardbtn2 = document.getElementById("card2");




// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];
var span2 = document.getElementsByClassName("close")[1];

// When the user clicks on the button, open the modal
//btn.onclick = function() {
//   modal.style.display = "block";
//}
cardbtn.onclick = function() {
  modal.style.display = "block";
}
cardbtn2.onclick = function() {
  modal2.style.display = "block";
}





// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}
span.onclick = function() {
    modal2.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";

    }
    else if(event.target == modal2) {
      modal2.style.display = "none";
    }
}

</script>

app/views/dailies/new.html.erb
<section class="view_container_daily">

  <section class="nav_daily">
    <h1 class="title_daily">데일리 뮤직</h1>
  </section>

  <section class="body_daily_new">

    <div class="preview_container">

      <div id="daily_color_modal">
        <p class="daily_title_modal">우리는 지금 어디</p>
      </div>
      <div class="daily_img_box_modal">
        <img class="daily_img_modal" src="/assets/daily_ex.jpg">
      </div>
      <div class="user_context_modal">

        <p class="daily_song_modal">잘 가요 로맨스 - 박선주</p>

        <input type="image" id="rec_btn" alt="rec"
            src="/assets/rec_btn_black.png" onclick="document.getElementById('rec_btn').src='/assets/rec_btn_red.png'">


        <p class="daily_text">랜덤 재생 모드로 음악을 듣다가 어느 순간 박선주의 ‘잘가요 로맨스’가 나온다. 전주 뒤에 첫 단어를 박선주가 노래하자마자 나는 도쿄의 좁디 좁은 호텔방에 누워있다. 그저 하얀 침대커버 왼쪽 모서리에 베개도 안 베고 오른쪽으로 돌아누운 채로
        </p>
      </div>
      <div class="user_context_modal2">

        <p class="daily_text2">바로 앞에 있는 나무 합판으로 만들어진 책상을 응시하고 있다. 온도는 반팔을 입고 있기에 딱 적당한 것 같은 온도, 창문 앞에 있는 싸구려 히터가 털털털 돌아가고 있는 것 같고, 건조한 것 같은 화장실은 살짝 문이 열려있다. 그냥 그렇게 있다.</p>

        <div class="by_user_nick_box">
          <span>by</span>
          <!-- <!— 사용자 데일리의 닉네임 (모달) —> -->
          <p class="daily_user_nick">피가로</p>
        </div>

      </div>

    </div>

    <section class="post_daily_form">

      <%= render "form" %>

    </section>

  </section>

  <section class="ad_daily">
    <p class="logo_daily">늘어진<br>카세트<br>테이프</p>
  </section>

</section>

<!-- <div class="post_daily">
  <section class="post_daily_preview">
  </section>
</div> -->

app/views/dailies/show.html.erb
<section class="view_container_daily">

  <section class="nav_daily">
    <h1 class="title_daily">데일리 뮤직</h1>
  </section>

  <section class="body_daily">
    <h3><%= @daily.daily_title %></h3>
    <p><%= @daily.body %></p>
  </section>
  <section class="ad_daily">
    <p class="logo_daily">늘어진<br>카세트<br>테이프</p>
  </section>

</section>

app/views/records/new.html.erb
<script>
  $(function(){
    var index = <%=raw @music_tscollection %>
    $(".admit_m").autocomplete({
      source: index
    });
  });
</script>


<!--Sign Up List page-->
<div class="admit_bg_img">
    <div class="admit_list_container">
    <div class="admit_list_title">자신의 인생 명곡 10곡을 등록해주세요.</div>

<!-- partial로 분리 예정 -->

<%= form_for @list do |f| %>

<div class="admit_list">
  <% 10.times do %>
    <%= f.text_field :music_id, class: "admit_m", placeholder: "음악을 등록해주세요", multiple: true %>
  <% end %>
</div>

<!-- <button type="submit" value="save" class="admit_list_btn">
  Sign Up
</button> -->

<%= f.submit "저장", class: "admit_list_btn" %>

<% end %>

  </div>
</div>

app/views/tapes/index.html.erb
<div class="main_tape_container">

  <div class="main_title_container">
    <h1 class="main_title">카세트 테이프</h1>
  </div>

  <div class="total_tape">

    <div class="total_intro">
      <p>당신의 플레이리스트와 꼭 맞는
        <%= @tapes.count %>개의 테이프를 준비했어요.</p>
    </div>

    <div class="total_tape_container">

      <% @tapes.each do |tape| %>
        <%= link_to tape_path tape do %>
          <div class="tape_theme_main">
            <img class="user_cover_main" src="/assets/cover_test.png">
            <div class="blend_box_main"></div>
            <img class="upload_tape_main" src="/assets/tapeskin_gray.png">
            <p class="tape_title_main"><%= tape.tape_title %></p>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

  <div class="logo_03_container">
    <p class="logo_03_txt">늘어진<br>카세트<br>테이프</p>
  </div>

</div>

app/views/tapes/show.html.erb
<div class="main_tape_container">

  <div class="main_title_container">
    <h1 class="main_title">카세트 테이프</h1>
  </div>

  <div class="total_tape">
    <div class="total_intro">
      <p>#번째 테이프</p>
    </div>

    <div class="tape_theme_main">
      <!-- <!— 사용자가 업로드하는 커버 이미지 —> -->
      <img class="user_cover_main" src="/assets/cover_test.png">
      <!-- <!— 선택 블렌딩 —> -->
      <div class="blend_box_main"></div>
      <!-- <!— 선택 스킨 —> -->
      <img class="upload_tape_main" src="/assets/tapeskin_purple.png">
      <!-- <!— 테이프 타이틀 —> -->
      <p class="tape_title_main"><%= @tape.tape_title %></p>
    </div>

    <div class="title_paper"></div>
    <div class="title_paper_p">
      <p class="tape_title_main"><%= @tape.tape_title %></p>
    </div>
    <div class="cover_paper">
      <img class="user_cover_main" src="/assets/cover_test.png">
    </div>

    <div class="songlist_paper_A">
      <% @list.each do |x| %>
          <p><%= x.ts %> <%= link_to "녹음녹음", add_records_path(x) %></p> <br>
      <% end %>
    </div>

    <div id="next">
      <div class="songlist_paper_B">
        <%# tape.each do |song| %>
          <p><%#= song.ts %></p>
        <%# end %>
      </div>
    </div>

    <div class="tape2_popup_btn">
      <%= link_to "수정", edit_tape_path(@tape) %>
      <a href="#" onclick="document.getElementById('next').style.display='none';document.getElementById('fade').style.display='none'">사이드 A
      </a>

      <a href="#" onclick="document.getElementById('next').style.display='block';document.getElementById('fade').style.display='block'">사이드 B
      </a>

      <%= link_to "닫기", :back %>
    </div>

  </div>

  <div class="logo_03_container">
    <p class="logo_03_txt">늘어진<br>카세트<br>테이프</p>
  </div>
</div>