config/routes.rb
Rails.application.routes.draw do
  get 'records/new'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'main#index'

  resources :musics
  resources :main
  resources :posts, only: [:index]
  resources :tapes
  resources :dailies
  resources :my_pages
  resources :records do
    get 'add/:id', :to => "records#add", as: 'add', on: :collection
  end

  get 'teasers/index'
  get 'main/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily.rb
class Daily < ApplicationRecord
  belongs_to :user
  has_many :musics, :as => :fantastic
end

app/models/music.rb
class Music < ApplicationRecord

end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :musics
end

app/models/tape.rb
class Tape < ApplicationRecord
  belongs_to :user
  belongs_to :m1, class_name: 'Music', foreign_key: 'm1', optional: true
  belongs_to :m2, class_name: 'Music', foreign_key: 'm2', optional: true
  belongs_to :m3, class_name: 'Music', foreign_key: 'm3', optional: true
  (4..10).to_a.each do |i|
    belongs_to "m#{i}".to_sym, class_name: 'Music', foreign_key: "m#{i}", optional: true
  end
  has_many :musics, :as => :fantastic
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tapes
  has_many :dailies
  has_many :records
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  def index

  end

  def new
    @daily = Daily.new

    @musics = Music.all

    @music_tscollection = Array.new()
    @musics.each do |music|
      @music_tscollection.push music.ts
    end
  end

  def create
    daily = Daily.new

    daily.user_id = current_user.id
    daily.daily_title = params[:daily][:daily_title]
    daily.musicN = params[:daily][:musicN]
    daily.body = params[:daily][:body]
    daily.save

    redirect_to new_daily_path
  end

  def update
    @daily = Daily.find_by.params[:daily_id]
  end

  def edit
    @daily = Daily.find_by.params[:daily_id]
  end

  def show
    @daily = Daily.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def show
  end

  # def show
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def new
    @list = Record.new


    @musics = Music.all

    @music_tscollection = Array.new()
    @musics.each do |music|
      @music_tscollection.push music.ts
    end
    # @list.user_id = current_user.id
    # @list.music_id = params[:record][:music_id]
    # @list.save
    #
    # redirect_to root_path
  end

  def create
    list = record_params.values

    list[0].each do |x|
      @list = Record.new
      @list.music_id = x
      @list.user_id = current_user.id
      @list.save
    end

    tape_list = Record.where(user_id: current_user.id).last(10)

    tape = Tape.new
    tape.tape_title = "인생열곡"
    tape.user_id = current_user.id
    tape.m1 = Music.find_by(id: tape_list[0].music_id)
    tape.m2 = Music.find_by(id: tape_list[1].music_id)
    tape.m3 = Music.find_by(id: tape_list[2].music_id)
    tape.m4 = Music.find_by(id: tape_list[3].music_id)
    tape.m5 = Music.find_by(id: tape_list[4].music_id)
    tape.m6 = Music.find_by(id: tape_list[5].music_id)
    tape.m7 = Music.find_by(id: tape_list[6].music_id)
    tape.m8 = Music.find_by(id: tape_list[7].music_id)
    tape.m9 = Music.find_by(id: tape_list[8].music_id)
    tape.m10 = Music.find_by(id: tape_list[9].music_id)
    tape.save

    redirect_to root_path
  end

  def add

    record = Record.new
    record.user_id = current_user.id
    record.music_id = params[:id]
    record.save

    redirect_back(fallback_location: root_path)
  end

  private
  def record_params
      params.require(:record).permit(:music_id => [])
    end
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  def index
    @tapes = Tape.all
  end

  def new
    @tape = Tape.new
    @musics = Music.all
    @music_tscollection = Music.pluck(:ts)
  end

  def edit
    @tape = Tape.find(params[:id])
    @musics = Music.all
    @music_tscollection = Music.pluck(:ts)
  end

  def update
    tape = Tape.find(params[:id])
    (1..10).to_a.each do |i|
      current_music = "m#{i}".to_sym
      music = nil
      if tape_params[current_music].present?
        music = Music.find_by_ts(tape_params[current_music][:ts])
      end
      tape_params[current_music] = music
    end
    tape.update!(tape_params)
    # tape.save!
    redirect_to edit_tape_path(tape), notice: "수정되었습니다."
  end

  def create
    @correct_music1 = Music.find_by_ts(params[:tape][:m1][:ts])
    @correct_music2 = Music.find_by_ts(params[:tape][:m2][:ts])
    @correct_music3 = Music.find_by_ts(params[:tape][:m3][:ts])
    @correct_music4 = Music.find_by_ts(params[:tape][:m4][:ts])
    @correct_music5 = Music.find_by_ts(params[:tape][:m5][:ts])
    @correct_music6 = Music.find_by_ts(params[:tape][:m6][:ts])
    @correct_music7 = Music.find_by_ts(params[:tape][:m7][:ts])
    @correct_music8 = Music.find_by_ts(params[:tape][:m8][:ts])
    @correct_music9 = Music.find_by_ts(params[:tape][:m9][:ts])
    @correct_music10 = Music.find_by_ts(params[:tape][:m10][:ts])

    tape = Tape.new

    tape.tape_title = params[:tape][:tape_title]
    tape.user_id = current_user.id
    tape.m1 = @correct_music1 || nil
    tape.m2 = @correct_music2 || nil
    tape.m3 = @correct_music3 || nil
    tape.m4 = @correct_music4 || nil
    tape.m5 = @correct_music5 || nil
    tape.m6 = @correct_music6 || nil
    tape.m7 = @correct_music7 || nil
    tape.m8 = @correct_music8 || nil
    tape.m9 = @correct_music9 || nil
    tape.m10 = @correct_music10 || nil
    tape.save
    redirect_to edit_tape_path(tape), notice: "테이프에 노래가 들어갔습니다."
  end


  def show
    @tape = Tape.find_by(id: params[:id])

    song = []
    song << @tape.m1
    song << @tape.m2
    song << @tape.m3
    song << @tape.m4
    song << @tape.m5
    song << @tape.m6
    song << @tape.m7
    song << @tape.m8
    song << @tape.m9
    song << @tape.m10

    @list = Music.where(id: song)
  end

  private

  def found_music(param)
    result = nil
    if param.is_a?(String)
      result = Music.find_by_ts(params[:tape][:m1])
    elsif param.is_a?(Music)
      result = Music.find_by_ts(params[:tape][:m1])
    end
    result
  end

  def set_data
    @tape = find_by.params[:tape_id]
  end

  def tape_params
    params.require(:tape).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/helpers/teasers_helper.rb
module TeasersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-123746599-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-123746599-1');
    </script>

    <title>NeulCatte</title>
    <%= csrf_meta_tags %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', params[:controller].split("/").first if NeulCatte::Application.assets.find_asset("#{params[:controller].split("/").first}.css") %>
    <%= javascript_include_tag 'application', params[:controller].split("/").first if NeulCatte::Application.assets.find_asset("#{params[:controller].split("/").first}.js") %>

    <meta property="og:title" content="늘어진 카세트 테이프" />
    <meta property="og:description" content="아날로그 감성을 담은 음악 추천 서비스" />
    <meta property="og:image" content="<%= asset_path("neulcatte_original.jpg") %>" />

  </head>

  <body>

<!-- Navbar -->
    <%= render "shared/nav" %>

    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<section id="header_mobile">
  <div class="wrapper">
  <% if user_signed_in? %>
    <nav id="main_nav_mobile"> 
      <ul>
      <%= link_to '테이프', tapes_path, class: "nav_item_mob" %>
      <%= link_to '데일리 뮤직', dailies_path, class: "nav_item_mob" %>
        <a href="javascript:postDisplay_menu();" class="nav_item_mob">포스트</a>
        <div id="dropdown_mob">
          <%= link_to '테이프', "/tapes/new", class: "nav_dropitem_mob1" %>
          <%= link_to '데일리 뮤직', "/dailies/new", class: "nav_dropitem_mob2" %>
        </div>
        <%= link_to '마이 페이지', my_pages_path, class: "nav_item_mob" %>
        <%= link_to '로그아웃', destroy_user_session_path, class: "nav_item_mob", method: 'delete' %>
      </ul>
    </nav>
    <a href="javascript:menuDisplay_mob();" id="trigger_mobile">메뉴</a>
    <%= link_to image_tag("logo.png", height: '56', width: '30'), root_path, class: "nav_logo_mobile" %>
    <% else %>
    <%= link_to '메뉴', new_user_session_path, class: "nav_item_login_mob" %>
    <%= link_to image_tag("logo.png", height: '56', width: '30'), root_path, class: "nav_logo_mobile" %>
    <% end %>
  </div>
</section>


<header id="header_web">

    <div class="blank">
    </div>
    
    <section class="main_nav">
      <nav id="main_nav">
          <ul class="nav_ul">
              <% if user_signed_in? %>
                <div class="nav_container">
                  <%= link_to image_tag("logo.png", height: '46', width: '20'), root_path, class: "nav_logo" %>
                  <%= link_to '늘카테', main_about_path, class: "nav_item" %>
                  <%= link_to '테이프', tapes_path, class: "nav_item" %>
                  <%= link_to '데일리 뮤직', dailies_path, class: "nav_item" %>
                  

                  <div class="dropdown">
                    <button onclick="myFunction()" class="postbtn">
                      포스트
                    </button>

                    <div id="post-dropdown" class="post-menu">
                      <%= link_to '테이프', "/tapes/new", class: "post-menu-down" %>
                      <%= link_to '데일리 뮤직', "/dailies/new", class: "post-menu-down" %>
                    </div>
                  </div>

                  <%= link_to '마이 페이지', my_pages_path, class: "nav_item" %>
                  <%= link_to '로그아웃', destroy_user_session_path, class: "nav_item", method: 'delete' %>
                  
                </div>
                <a href="#" id="trigger">메뉴</a>
                <% else %>
                  <div class="nav_container">
                    <%= link_to image_tag("logo.png", height: '46', width: '20'), root_path, class: "nav_logo" %>
                    <%= link_to '늘어진 카세트 테이프', main_about_path, class: "nav_logotext" %>
                    <%= link_to '로그인', new_user_session_path, class: "nav_item" %>
                    
                  </div>
                <% end %>

          </ul>
          
      </nav>
    </section>
  </header>
  
  <script>
    $(function () {
      var trigger = $('#trigger');
      var menu = $('nav ul');
      $(trigger).on('click', function (e) {
        e.preventDefault();
        menu.slideToggle();
      });
      $(window).resize(function () {
        var w = $(window).width();
        if (w > 320 && menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });
    
  </script>


<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
document.getElementById("post-dropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
if (!event.target.matches('.postbtn')) {

var dropdowns = document.getElementsByClassName("post-menu");
var i;
for (i = 0; i < dropdowns.length; i++) {
  var openDropdown = dropdowns[i];
  if (openDropdown.classList.contains('show')) {
    openDropdown.classList.remove('show');
  }
}
}
}

function menuDisplay_mob(){
    var nav = document.getElementById("main_nav_mobile");
    if(nav.style.display=='none'){
      nav.style.display = 'block';
    }else{
      nav.style.display = 'none';
    }
}
function postDisplay_menu(){
    var post = document.getElementById("dropdown_mob");
    var changeheight = document.getElementById("main_nav_mobile");
    if(post.style.display=='none'){
      post.style.display = 'flex';
      changeheight.style.height='60vw';
    }else{
      post.style.display = 'none';
      changeheight.style.height='42vw';
    }
}



</script>